apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hdh0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hdh0
    app.kubernetes.io/part-of: ci10t-786-0013-app
  name: devfile-sample-hdh0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hdh0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hdh0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0013-tenant/ci10t-786-0013-app/devfile-sample-hdh0@sha256:87cba4533a6e28585b85fae98900bc65363450a2cb6c9cfb5dd8b2542b247f44
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
